# Site settings
course_code: AIL7024 
course_name: "INTRODUCTION TO MACHINE LEARNING"
course_description: "This course offers a detailed introduction to core and advanced topics in Machine Learning, suitable for postgraduate students. The syllabus covers decision trees, regression models, generalized linear models, generative classifiers, and support vector machines, with emphasis on both theoretical concepts and their practical implementations. Students will explore modern techniques such as ensemble learning, dimensionality reduction, neural networks, CNNs, RNNs, and transformers. Lectures are supported by supplementary readings and detailed scribes to reinforce learning. The course includes assignments and quizzes that combine theoretical analysis with coding exercises using real-world data. A half-semester-long project will require students to design and implement complete ML pipelines, from preprocessing to evaluation."
course_semester: "Semester I, 2025-26"

baseurl: "/AIL7024-2501" # the subpath of your site, e.g. /blog/
url: "http://lcs2-iitd.github.io/" # the base hostname & protocol for your site

schoolname: "IIT Delhi"
schoolurl: "https://www.lcs2.in"
twitter_username: lcs2lab 

address: |
    Laboratory for Computational Social Systems (LCS2)
    Indian Institute of Technology Delhi
    Hauz Khas, New Delhi - 110016, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-FYNEGWXPQZ

### Do not change the following unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
